// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qcC97Zf_zMVGFj7J29Y6Kzc3AOlBW4g',
    appId: '1:549768203410:web:b54d15531ef30fc2beea4b',
    messagingSenderId: '549768203410',
    projectId: 'foodiex-545b6',
    authDomain: 'foodiex-545b6.firebaseapp.com',
    storageBucket: 'foodiex-545b6.firebasestorage.app',
    measurementId: 'G-R421KBQT8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6zYc7IqCAtOaDTqX4snpfuN76gvkoWsI',
    appId: '1:549768203410:android:f5cbd043cfcca028beea4b',
    messagingSenderId: '549768203410',
    projectId: 'foodiex-545b6',
    storageBucket: 'foodiex-545b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPczkaUsoQYchGXAWLVI5z56yYkQSUQ24',
    appId: '1:549768203410:ios:358a8447d7fb4ab8beea4b',
    messagingSenderId: '549768203410',
    projectId: 'foodiex-545b6',
    storageBucket: 'foodiex-545b6.firebasestorage.app',
    iosBundleId: 'com.example.foodiex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPczkaUsoQYchGXAWLVI5z56yYkQSUQ24',
    appId: '1:549768203410:ios:358a8447d7fb4ab8beea4b',
    messagingSenderId: '549768203410',
    projectId: 'foodiex-545b6',
    storageBucket: 'foodiex-545b6.firebasestorage.app',
    iosBundleId: 'com.example.foodiex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qcC97Zf_zMVGFj7J29Y6Kzc3AOlBW4g',
    appId: '1:549768203410:web:78734a39967ae97dbeea4b',
    messagingSenderId: '549768203410',
    projectId: 'foodiex-545b6',
    authDomain: 'foodiex-545b6.firebaseapp.com',
    storageBucket: 'foodiex-545b6.firebasestorage.app',
    measurementId: 'G-M7307XCN3F',
  );
}
